spring.application.name=Dental-Fine-BackEnd

spring.datasource.url=jdbc:postgresql://localhost:5432/dentalfine_db
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=root


